[build]
  publish ="public/"
  command = "sed -i s/HEADER_PLACEHOLDER/pixie:${BASIC_AUTH}/g netlify.toml && yarn install && yarn lint && gatsby build"

[build.environment]
  # Staging environment.
  TRACKING_ID = "UA-141615052-1"
  MAILCHIMP_ENDPOINT = "https://pixielabs.us20.list-manage.com/subscribe/post?u=b962bcefc9d3e650c45145a13&id=2d84999f8d"

[context.production]
  # No password on prod.
  command = "sed -i 's|HEADER_PLACEHOLDER||g' netlify.toml && yarn install && yarn lint && gatsby build"

[context.production.environment]
  TRACKING_ID = "UA-141511669-1"
  MAILCHIMP_ENDPOINT = "https://pixielabs.us20.list-manage.com/subscribe/post?u=b962bcefc9d3e650c45145a13&id=2d84999f8d"

[[redirects]]
  from = "/blog"
  to = "https://blog.pixielabs.ai"

[[redirects]]
  from = "/docs"
  to = "https://docs.pixielabs.ai"

[[headers]]
  for = "/*"
  [headers.values]
    Basic-Auth = "HEADER_PLACEHOLDER"
